"""Initial migration.

Revision ID: 63c71a4d2554
Revises: 
Create Date: 2024-11-22 14:05:54.447126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c71a4d2554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_description_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=50), nullable=False),
    sa.Column('primary_breed', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('primary_color', sa.String(length=50), nullable=False),
    sa.Column('maturity_size', sa.String(length=50), nullable=False),
    sa.Column('fur_length', sa.String(length=50), nullable=False),
    sa.Column('vaccinated', sa.String(length=10), nullable=False),
    sa.Column('dewormed', sa.String(length=10), nullable=False),
    sa.Column('sterilized', sa.String(length=10), nullable=False),
    sa.Column('health', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_description_requests')
    # ### end Alembic commands ###
